name: Unit Tests

on:
  push:
    branches: ["main"] # Dispara o pipeline quando houver push na branch main
  pull_request:
    branches: ["main"] # Dispara o pipeline quando houver PR para a main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: pnpm run test
